"""PATCH: added server default value for version field in inventory section table

Revision ID: 0473e664ad51
Revises: 08fc59edd752
Create Date: 2026-02-22 03:45:44.586206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0473e664ad51'
down_revision: Union[str, Sequence[str], None] = '08fc59edd752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section_inventory', 'version',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section_inventory', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
