"""ADD: added section_inventory table to track the booking availibility

Revision ID: 08fc59edd752
Revises: 4090dcbf5572
Create Date: 2026-02-22 03:02:35.171731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08fc59edd752'
down_revision: Union[str, Sequence[str], None] = '4090dcbf5572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_inventory',
    sa.Column('section_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('total_capacity', sa.INTEGER(), nullable=False),
    sa.Column('available_capacity', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_capacity >= 0', name='check_available_capacity'),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_inventory')
    # ### end Alembic commands ###
