"""added user table and otp table

Revision ID: 0ec8a3f9dedb
Revises: 
Create Date: 2026-02-16 19:12:33.538023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec8a3f9dedb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('country_code', sa.CHAR(length=3), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'phone_number', name='uq_country_phone')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('country_code', sa.CHAR(length=3), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'phone_number', name='uq_country_phone'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('otp')
    # ### end Alembic commands ###
