"""ADD: added section_inventory table to track the booking availibility

Revision ID: 4090dcbf5572
Revises: 66c7ad79d374
Create Date: 2026-02-22 02:57:16.404099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4090dcbf5572'
down_revision: Union[str, Sequence[str], None] = '66c7ad79d374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
