"""PATCH: added a sections field in event table which will store the section ids inside the table

Revision ID: 66c7ad79d374
Revises: 86c3484811b9
Create Date: 2026-02-21 00:28:01.078690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66c7ad79d374'
down_revision: Union[str, Sequence[str], None] = '86c3484811b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('sections', postgresql.ARRAY(sa.UUID(as_uuid=False)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'sections')
    # ### end Alembic commands ###
