"""PATCH: added default function to generate the uuidv7 for generating primary key

Revision ID: 71465faec265
Revises: 96ede4b5a62b
Create Date: 2026-02-22 15:45:42.274923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71465faec265'
down_revision: Union[str, Sequence[str], None] = '96ede4b5a62b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuidv7()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
