"""PATCH: changed incorrect field name i section table

Revision ID: 86c3484811b9
Revises: 51e34a2f1fab
Create Date: 2026-02-21 00:07:37.041277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c3484811b9'
down_revision: Union[str, Sequence[str], None] = '51e34a2f1fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('total_capacity', sa.Integer(), nullable=False))
    op.drop_column('section', 'total_capapcity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('total_capapcity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('section', 'total_capacity')
    # ### end Alembic commands ###
