"""PATCH: added composite key on user_id and status hold

Revision ID: 9d655ad0a250
Revises: b0aa71e9e94d
Create Date: 2026-03-07 09:47:02.255717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d655ad0a250'
down_revision: Union[str, Sequence[str], None] = 'b0aa71e9e94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_user_id_status_hold'), table_name='bookings', postgresql_where="(status = 'HOLD'::booking_status)")
    op.create_index('idx_user_id_status_hold', 'bookings', ['user_id', 'status'], unique=True, postgresql_where=sa.text("status = 'HOLD'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id_status_hold', table_name='bookings', postgresql_where=sa.text("status = 'HOLD'"))
    op.create_index(op.f('idx_user_id_status_hold'), 'bookings', ['user_id', 'status'], unique=False, postgresql_where="(status = 'HOLD'::booking_status)")
    # ### end Alembic commands ###
