"""PATCH: added event_date field in event model

Revision ID: a62dbe8e4227
Revises: 71465faec265
Create Date: 2026-02-22 18:44:55.984227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62dbe8e4227'
down_revision: Union[str, Sequence[str], None] = '71465faec265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_date', sa.DATE(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_date')
    # ### end Alembic commands ###
