"""PATCH: added composite key on user_id and status hold

Revision ID: b0aa71e9e94d
Revises: ee4a55c62adf
Create Date: 2026-03-07 09:44:30.859439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0aa71e9e94d'
down_revision: Union[str, Sequence[str], None] = 'ee4a55c62adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_id_status_hold', 'bookings', ['user_id', 'status'], unique=False, postgresql_where=sa.text("status = 'HOLD'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id_status_hold', table_name='bookings', postgresql_where=sa.text("status = 'HOLD'"))
    # ### end Alembic commands ###
