"""PATCH: have to change the column name in snake case

Revision ID: c2e5eabc5367
Revises: dfc6dd1420c8
Create Date: 2026-02-18 22:06:03.660221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e5eabc5367'
down_revision: Union[str, Sequence[str], None] = 'dfc6dd1420c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('ip_address', sa.Text(), nullable=True))
    op.add_column('session', sa.Column('user_agent', sa.Text(), nullable=True))
    op.drop_column('session', 'userAgent')
    op.drop_column('session', 'ipAddress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('ipAddress', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('userAgent', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('session', 'user_agent')
    op.drop_column('session', 'ip_address')
    # ### end Alembic commands ###
