"""changed type of otp from string to text

Revision ID: d999ec6b3d5a
Revises: 3f9df0a67ad1
Create Date: 2026-02-16 20:46:22.733959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd999ec6b3d5a'
down_revision: Union[str, Sequence[str], None] = '3f9df0a67ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp', 'otp',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp', 'otp',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
