"""PATCH: removed relationship setup from session model for orm

Revision ID: dfc6dd1420c8
Revises: b25392d56ea8
Create Date: 2026-02-18 21:49:42.762524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc6dd1420c8'
down_revision: Union[str, Sequence[str], None] = 'b25392d56ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
