"""PATCH: added expires_at field in booking table

Revision ID: ee4a55c62adf
Revises: b483440e5246
Create Date: 2026-02-24 18:37:07.316183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4a55c62adf'
down_revision: Union[str, Sequence[str], None] = 'b483440e5246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('expires_at', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'expires_at')
    # ### end Alembic commands ###
