"""PATCH: changed all the import from sql alchemy orm

Revision ID: ee737a489d49
Revises: 0473e664ad51
Create Date: 2026-02-22 04:08:44.223605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee737a489d49'
down_revision: Union[str, Sequence[str], None] = '0473e664ad51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
